---
server:
  port: 0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://discUser:discPassword@localhost:8082/eureka/
spring:
  security:
    user:
      name: configUser
      password: configPassword
      roles: SYSTEM
