---
spring:
  application:
    name: tipsy-security
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
#---
#server:
#  port: 8090
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: http://discUser:discPassword@localhost:8082/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${random.int}
#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  security:
#    user:
#      name: configUser
#      password: configPassword
#      roles: SYSTEM
#  profiles:
#    active: development
#connection:
#  success: PropertiesConnectionSuccessful
